=== espressif/openocd-esp32/tcl/esp-config-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/espressif/openocd-esp32/blob/master/tcl/esp-config-schema.json",
    "title": "esp_config",
    "description": "esp_config",
    "type": "object",
    "properties": {
        "version": {
            "description": "Metadata file version",
            "type": "string"
        },
        "targets": {
            "description": "List of targets",
            "type": "array",
            "items": {
                "$ref": "#/definitions/targetsInfo"
            }
        },
        "interfaces": {
            "description": "List of debug interfaces",
            "type": "array",
            "items": {
                "$ref": "#/definitions/interfacesInfo"
            }
        },
        "boards": {
            "description": "List of boards",
            "type": "array",
            "items": {
                "$ref": "#/definitions/boardsInfo"
            }
        },
        "options": {
            "description": "List of options",
            "type": "array",
            "items": {
                "$ref": "#/definitions/optionsInfo"
            }
        },
        "openocd_feature_flags_ide": {
            "$ref": "#/definitions/featureFlagsIde"
        }
    },
    "required": [
        "version",
        "targets",
        "boards",
        "options"
    ],
    "definitions": {
        "targetsInfo": {
            "type": "object",
            "description": "Information about a target",
            "properties": {
                "id": {
                    "$ref": "#/definitions/chipID",
                    "description": "ID of the target e.g. 'esp32'"
                },
                "name": {
                    "description": "Name of the target e.g. 'ESP32'",
                    "type": "string"
                },
                "idcode": {
                    "description": "JTAG IDCODE of the chip",
                    "type": "string"
                },
                "ocdid": {
                    "description": "OCDID of Xtensa chip",
                    "type": "string"
                }
            },
            "required": [
                "id",
                "name"
            ]
        },
        "interfacesInfo": {
            "type": "object",
            "description": "Information about debug interface",
            "properties": {
                "id": {
                    "description": "Interface ID. Actually this is OpenOCD debug adapter driver name.",
                    "type": "string"
                },
                "config_file": {
                    "description": "Config file of debug interface e.g. 'ftdi/esp_ftdi.cfg'. Path relative to 'interface' sub-dir.",
                    "type": "string"
                },
                "command": {
                    "description": "Command for the debug interface driver, e.g. 'ftdi'",
                    "type": "string"
                }
            }
        },
        "boardsInfo": {
            "type": "object",
            "description": "Information about a board",
            "properties": {
                "name": {
                    "description": "Name of the board e.g. 'ESP-WROVER-KIT 1.8V'",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the board e.g. 'ESP-WROVER-KIT with 1.8V ESP32-WROVER-B module'",
                    "type": "string"
                },
                "target": {
                    "description": "Target of the board e.g. 'esp32s2'",
                    "$ref": "#/definitions/chipID"
                },
                "config_files": {
                    "description": "Config Files of the board e.g. 'board/esp32-wrover-kit-1.8v.cfg'",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "interface": {
                    "description": "Interface ID. Actually this is OpenOCD debug adapter driver name.",
                    "type": "string",
                    "$ref": "#/definitions/interfacesInfo/properties/id"
                },
                "location": {
                    "description": "Location of the board, e.g. for USB it will look like 'usb://<bus>-<port>[.<port>]...'.",
                    "type": "string"
                }
            },
            "required": [
                "name",
                "description",
                "target",
                "config_files"
            ]
        },
        "optionsInfo": {
            "type": "object",
            "description": "Information about options",
            "properties": {
                "name": {
                    "description": "Name of the option e.g. 'ESP_FLASH_VOLTAGE'",
                    "type": "string"
                },
                "values": {
                    "description": "Values of the option e.g. 'default', '1,8', 'auto'",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "Description of the option e.g. 'Flash voltage', 'Flash size'",
                    "type": "string"
                },
                "type": {
                    "description": "Type of the option e.g. 'choice'",
                    "$ref": "#/definitions/optionTypes"
                },
                "targets": {
                    "description": "Targets for which the option is defined e.g. 'esp32', 'esp32s2'",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chipID"
                    }
                }
            },
            "required": [
                "name",
                "values",
                "description",
                "type"
            ]
        },
        "chipID": {
            "type": "string",
            "description": "Name of the chip target",
            "enum": [
                "esp32",
                "esp32s2",
                "esp32s3",
                "esp32c2",
                "esp32c3",
                "esp32c5",
                "esp32c6",
                "esp32c61",
                "esp32h2",
                "esp32h21",
                "esp32p4",
                "esp32h4",
                "esp32s31"
            ]
        },
        "optionTypes": {
            "type": "string",
            "description": "Option types",
            "enum": [
                "choice",
                "choice_edit"
            ]
        },
        "featureFlagsIde": {
            "description": "Defines the OpenOCD features available in this release impacting IDE integration (e.g. Espressif IDE or VSCode extension).",
            "type": "object",
            "properties": {
                "supports_new_port_syntax": {
                    "type": "boolean",
                    "description": "If true, IDEs should use 'gdb port' / 'telnet port' / 'tcl port' instead of legacy '*_port' options.",
                    "default": false
                }
            }
        }
    }
}

=== espressif/openocd-esp32/tcl/esp-config.json
{
    "version": "1.0",
    "targets": [
        {
            "id": "esp32",
            "name": "ESP32",
            "idcode": "0x120034e5",
            "ocdid": "0x0733bff2"
        },
        {
            "id": "esp32s2",
            "name": "ESP32-S2",
            "idcode": "0x120034e5",
            "ocdid": "0x03339fd2"
        },
        {
            "id": "esp32s3",
            "name": "ESP32-S3",
            "idcode": "0x120034e5",
            "ocdid": "0x0b339fd2"
        },
        {
            "id": "esp32c2",
            "name": "ESP32-C2",
            "idcode": "0x0000cc25"
        },
        {
            "id": "esp32c3",
            "name": "ESP32-C3",
            "idcode": "0x00005c25"
        },
        {
            "id": "esp32c5",
            "name": "ESP32-C5",
            "idcode": "0x00017c25"
        },
        {
            "id": "esp32c6",
            "name": "ESP32-C6",
            "idcode": "0x0000dc25"
        },
        {
            "id": "esp32c61",
            "name": "ESP32-C61",
            "idcode": "0x00014c25"
        },
        {
            "id": "esp32h2",
            "name": "ESP32-H2",
            "idcode": "0x00010c25"
        },
        {
            "id": "esp32h21",
            "name": "ESP32-H21",
            "idcode": "0x00019c25"
        },
        {
            "id": "esp32p4",
            "name": "ESP32-P4",
            "idcode": "0x00012c25"
        },
        {
            "id": "esp32h4",
            "name": "ESP32-H4",
            "idcode": "0x0001cc25"
        },
        {
            "id": "esp32s31",
            "name": "ESP32-S31",
            "idcode": "0x00020C25"
        }
    ],
    "interfaces": [
        {
            "id": "ftdi",
            "config_file": "ftdi/esp_ftdi.cfg",
            "command": "ftdi"
        },
        {
            "id": "esp_usb_jtag",
            "config_file": "esp_usb_jtag.cfg",
            "command": "espusbjtag"
        },
        {
            "id": "esp_usb_bridge",
            "config_file": "esp_usb_bridge.cfg",
            "command": "espusbjtag"
        }
    ],
    "boards": [
        {
            "name": "ESP-WROVER-KIT 3.3V",
            "description": "ESP-WROVER-KIT with 3.3V ESP32-WROVER-B module",
            "target": "esp32",
            "interface": "ftdi",
            "config_files": [
                "board/esp32-wrover-kit-3.3v.cfg"
            ]
        },
        {
            "name": "ESP-WROVER-KIT 1.8V",
            "description": "ESP-WROVER-KIT with 1.8V ESP32-WROVER-B module",
            "target": "esp32",
            "interface": "ftdi",
            "config_files": [
                "board/esp32-wrover-kit-1.8v.cfg"
            ]
        },
        {
            "name": "ESP32-ETHERNET-KIT",
            "description": "ESP32-ETHERNET-KIT with ESP32-WROVER-E module",
            "target": "esp32",
            "interface": "ftdi",
            "config_files": [
                "board/esp32-ethernet-kit-3.3v.cfg"
            ]
        },
        {
            "name": "ESP32 chip (via ESP-PROG)",
            "description": "ESP32 debugging via ESP-PROG board",
            "target": "esp32",
            "interface": "ftdi",
            "config_files": [
                "interface/ftdi/esp_ftdi.cfg",
                "target/esp32.cfg"
            ]
        },
        {
            "name": "ESP32 chip (via ESP-PROG-2)",
            "description": "ESP32 debugging via ESP-PROG-2 board",
            "target": "esp32",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-SOLO-1 module (via ESP-PROG)",
            "description": "ESP32-SOLO-1 debugging via ESP-PROG board",
            "target": "esp32",
            "interface": "ftdi",
            "config_files": [
                "interface/ftdi/esp_ftdi.cfg",
                "target/esp32-solo-1.cfg"
            ]
        },
        {
            "name": "ESP32-S2-KALUGA-1",
            "description": "ESP32-S2-KALUGA-1 kit",
            "target": "esp32s2",
            "interface": "ftdi",
            "config_files": [
                "board/esp32s2-kaluga-1.cfg"
            ]
        },
        {
            "name": "ESP32-S2 chip (via ESP-PROG)",
            "description": "ESP32-S2 debugging via ESP-PROG board",
            "target": "esp32s2",
            "interface": "ftdi",
            "config_files": [
                "interface/ftdi/esp_ftdi.cfg",
                "target/esp32s2.cfg"
            ]
        },
        {
            "name": "ESP32-S2 chip (via ESP-PROG-2)",
            "description": "ESP32-S2 debugging via ESP-PROG-2 board",
            "target": "esp32s2",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32s2-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-S3 chip (via builtin USB-JTAG)",
            "description": "ESP32-S3 debugging via builtin USB-JTAG",
            "target": "esp32s3",
            "interface": "esp_usb_jtag",
            "config_files": [
                "board/esp32s3-builtin.cfg"
            ]
        },
        {
            "name": "ESP32-S3 chip (via ESP-PROG)",
            "description": "ESP32-S3 debugging via ESP-PROG board",
            "target": "esp32s3",
            "interface": "ftdi",
            "config_files": [
                "interface/ftdi/esp_ftdi.cfg",
                "target/esp32s3.cfg"
            ]
        },
        {
            "name": "ESP32-S3 chip (via ESP-PROG-2)",
            "description": "ESP32-S3 debugging via ESP-PROG-2 board",
            "target": "esp32s3",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32s3-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-C2 chip (via ESP-PROG)",
            "description": "ESP32-C2 debugging via ESP-PROG board",
            "target": "esp32c2",
            "interface": "ftdi",
            "config_files": [
                "board/esp32c2-ftdi.cfg"
            ]
        },
        {
            "name": "ESP32-C2 chip (via ESP-PROG-2)",
            "description": "ESP32-C2 debugging via ESP-PROG-2 board",
            "target": "esp32c2",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32c2-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-C3 chip (via builtin USB-JTAG)",
            "description": "ESP32-C3 debugging via builtin USB-JTAG",
            "target": "esp32c3",
            "interface": "esp_usb_jtag",
            "config_files": [
                "board/esp32c3-builtin.cfg"
            ]
        },
        {
            "name": "ESP32-C3 chip (via ESP-PROG)",
            "description": "ESP32-C3 debugging via ESP-PROG board",
            "target": "esp32c3",
            "interface": "ftdi",
            "config_files": [
                "board/esp32c3-ftdi.cfg"
            ]
        },
        {
            "name": "ESP32-C3 chip (via ESP-PROG-2)",
            "description": "ESP32-C3 debugging via ESP-PROG-2 board",
            "target": "esp32c3",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32c3-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-C5 chip (via builtin USB-JTAG)",
            "description": "ESP32-C5 debugging via builtin USB-JTAG",
            "target": "esp32c5",
            "interface": "esp_usb_jtag",
            "config_files": [
                "board/esp32c5-builtin.cfg"
            ]
        },
        {
            "name": "ESP32-C5 chip (via ESP-PROG)",
            "description": "ESP32-C5 debugging via ESP-PROG board",
            "target": "esp32c5",
            "interface": "ftdi",
            "config_files": [
                "board/esp32c5-ftdi.cfg"
            ]
        },
        {
            "name": "ESP32-C5 chip (via ESP-PROG-2)",
            "description": "ESP32-C5 debugging via ESP-PROG-2 board",
            "target": "esp32c5",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32c5-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-C5 chip with LP core (via builtin USB-JTAG)",
            "description": "ESP32-C5 with LP core debugging via builtin USB-JTAG",
            "target": "esp32c5",
            "interface": "esp_usb_jtag",
            "config_files": [
                "board/esp32c5-lpcore-builtin.cfg"
            ]
        },
        {
            "name": "ESP32-C5 chip with LP core (via ESP-PROG)",
            "description": "ESP32-C5 with LP core debugging via ESP-PROG board",
            "target": "esp32c5",
            "interface": "ftdi",
            "config_files": [
                "board/esp32c5-lpcore-ftdi.cfg"
            ]
        },
        {
            "name": "ESP32-C5 chip with LP core (via ESP-PROG-2)",
            "description": "ESP32-C5 with LP core debugging via ESP-PROG-2 board",
            "target": "esp32c5",
            "interface": "esp_usb_bridge",
            "config_files": [
                "board/esp32c5-lpcore-bridge.cfg"
            ]
        },
        {
            "name": "ESP32-C6 chip (via builtin USB-JTAG)",
            "description": "ESP32-C6 debugging via builtin USB-JTAG",
            "target": "esp32c6",
            "interface": "esp_usb_jtag",
            "config_files": [
                "board/esp32c6-builtin.cfg"
            ]
        },
        {
            "name": "ESP32-C6 chip (via ESP-PROG)",
            "description": "ESP32-C6 debugging via ESP-PROG board",
            "target": "esp32c6",
            "interface": "ftdi",
            "config_files": [
                "board/esp32c6-ftdi.cfg"
            ]
        },
        {
            "name": "ESP32-C6 chip (via ESP-PROG-2)",
